import { Gasoek_One, Roboto } from "next/font/google";
import "./globals.css";

const gasoekOne = Gasoek_One({
  variable: "--font-gasoek-one",
  weight: "400",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gasoekOne.variable} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
